"use client";
import Link from "next/link";
import { useState } from "react";
import { useMutation, usePaginatedQuery, useQuery } from "convex/react";
import { organizationApi } from "@/lib/organization-api";
import type { FunctionReturnType } from "convex/server";
import type { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { DocumentUpload } from "@/components/admin/document-upload";
import { DocumentReview, type ReviewItem } from "@/components/admin/document-review";
import { VersionHistory } from "@/components/admin/resource-register";
import { StepUpDialog } from "@/components/admin/step-up-dialog";
const inputClass = "min-h-11 w-full rounded-md border bg-background px-3 font-normal";
export function OrganizationResources({ organizationId }: { organizationId: Id<"organizations"> }) {
  const workspace = useQuery(organizationApi.organizations.getWorkspace, { organizationId });
  const { results, status, loadMore } = usePaginatedQuery(organizationApi.organizationContent.listResources, { organizationId }, { initialNumItems: 20 });
  const create = useMutation(organizationApi.organizationContent.createResource);
  const [creating, setCreating] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  return <div className="space-y-6"><header className="flex items-center justify-between"><h1 className="text-3xl font-semibold">Documents</h1>{workspace?.canManage && workspace.jurisdiction && <Button onClick={() => setCreating(v => !v)}>{creating ? "Cancel" : "Add document"}</Button>}</header><p className="text-sm text-muted-foreground">Create a document record, upload the original, and have an independent reviewer approve it before publication.</p>{!workspace?.jurisdiction && <p>Contact your platform administrator to provision your jurisdiction.</p>}
    {creating && <form className="grid gap-4 rounded-lg border p-5 sm:grid-cols-2" onSubmit={async event => { event.preventDefault(); if (!workspace?.jurisdiction) return; const form = new FormData(event.currentTarget); const text = (name: string) => String(form.get(name) ?? ""); setBusy(true); setError(""); try { await create({ jurisdictionId: workspace.jurisdiction.id, type: text("type"), title: text("title"), issuer: text("issuer"), officialCitation: text("officialCitation"), sourceUrl: text("sourceUrl"), effectiveDate: text("effectiveDate"), topics: [], reason: text("reason") }); setCreating(false); } catch { setError("The document couldn't be created. Check required fields and ensure its citation is unique."); } finally { setBusy(false); } }}>
      {[["title", "Document title"], ["issuer", "Issuing organization"], ["officialCitation", "Official citation or reference"], ["sourceUrl", "Official source URL"], ["effectiveDate", "Effective date"], ["reason", "Reason for adding"]].map(([name, label]) => <label key={name} className="grid gap-2 text-sm font-medium">{label}<input name={name} required maxLength={name === "sourceUrl" ? 500 : 300} minLength={name === "reason" ? 3 : undefined} type={name === "effectiveDate" ? "date" : name === "sourceUrl" ? "url" : "text"} className={inputClass} /></label>)}<label className="grid gap-2 text-sm font-medium">Document type<select name="type" defaultValue="policy" className={inputClass}>{["constitution", "act", "regulation", "ordinance", "judgment", "policy", "guidance"].map(type => <option key={type}>{type}</option>)}</select></label><Button disabled={busy} className="self-end">{busy ? "Creating…" : "Create document"}</Button>{error && <p role="alert">{error}</p>}
    </form>}
    <ul className="divide-y rounded-lg border">{results.map(resource => <li key={resource._id} className="p-4"><Link href={`/organizations/${organizationId}/resources/${resource._id}`} className="font-medium underline underline-offset-4">{resource.title}</Link><p className="mt-1 text-sm text-muted-foreground">{resource.officialCitation} · {resource.status}{resource.activeVersionId ? " · Published" : " · Not published"}</p></li>)}</ul>{status === "LoadingFirstPage" ? <p role="status">Loading documents…</p> : !results.length ? <p>No documents yet.</p> : null}{status === "CanLoadMore" && <Button variant="outline" onClick={() => loadMore(20)}>Load more</Button>}
  </div>;
}
export function OrganizationDocument({ organizationId, resourceId }: { organizationId: Id<"organizations">; resourceId: Id<"legalResources"> }) {
  const detail = useQuery(organizationApi.organizationContent.getResource, { organizationId, resourceId });
  const { results, status, loadMore } = usePaginatedQuery(organizationApi.organizationContent.listVersions, { organizationId, resourceId }, { initialNumItems: 10 });
  const approve = useMutation(organizationApi.organizationContent.approveVersion), reject = useMutation(organizationApi.organizationContent.rejectVersion), publish = useMutation(organizationApi.organizationContent.publishVersion), unpublish = useMutation(organizationApi.organizationContent.unpublishVersion), rollback = useMutation(organizationApi.organizationContent.rollbackVersion);
  if (!detail) return <p role="status">Loading document…</p>;
  const resource = detail.resource;
  const items: ReviewItem[] = results.flatMap(row => { const status = row.status; return status === "ready_for_review" || status === "approved" || status === "publishing" || status === "published" || status === "superseded" ? [{ ...row, status }] : []; });
  return <div className="space-y-8"><header><Link href={`/organizations/${organizationId}/resources`} className="text-sm underline">Documents</Link><h1 className="mt-4 text-3xl font-semibold">{resource.title}</h1><p className="mt-2 text-muted-foreground">{resource.officialCitation}</p></header>{detail.role === "manager" && <DocumentUpload resourceId={resourceId} resourceStatus={resource.status} defaultSourceUrl={resource.sourceUrl} defaultEffectiveAt={resource.effectiveDate} maxBytes={detail.maxBytes} onUpload={async input => { const form = new FormData(); form.set("file", input.file); form.set("sourceUrl", input.sourceUrl); form.set("effectiveAt", input.effectiveAt); const response = await fetch(`/api/organizations/${organizationId}/resources/${resourceId}/upload`, { method: "POST", body: form, signal: AbortSignal.timeout(60000) }); if (!response.ok) throw new Error("Upload could not be confirmed."); }} />}
    {detail.role === "manager" && <ResourceSettings resource={resource} />}<section className="rounded-lg bg-[oklch(97%_0.012_82)] p-5 text-[oklch(23%_0.05_252)]"><h2 className="mb-4 text-xl font-semibold">Version history</h2><VersionHistory versions={results} />{results.filter(row => row.status === "publishing" || row.status === "published").map(row => <PublicationStatus key={row.id} versionId={row.id} />)}{status === "CanLoadMore" && <Button variant="outline" onClick={() => loadMore(10)}>Load more versions</Button>}</section>
    <section className="rounded-lg bg-[oklch(97%_0.012_82)] p-5 text-[oklch(23%_0.05_252)]"><DocumentReview items={items} actions={{ approve, reject, publish, unpublish, rollback }} canReview={detail.role === "reviewer"} operationsHref={`/organizations/${organizationId}/resources/${resourceId}`} /></section>
  </div>;
}
export function OrganizationSettings({ organizationId }: { organizationId: Id<"organizations"> }) {
  const data = useQuery(organizationApi.organizations.getWorkspace, { organizationId });
  const setVisibility = useMutation(organizationApi.organizations.setVisibility), setPresentation = useMutation(organizationApi.organizations.setPresentation);
  const [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  const [risk, setRisk] = useState<{ key: string; visibility: "public" | "members" } | null>(null);
  if (!data) return <p role="status">Loading jurisdiction…</p>;
  return <div className="max-w-2xl space-y-5"><h1 className="text-3xl font-semibold">Jurisdiction</h1><h2 className="text-xl">{data.jurisdiction?.name ?? "Not provisioned"}</h2><p className="text-sm">{data.hasPublishedDocuments ? "Published documents available." : "No published document is available yet."} <Link className="underline" href={`/organizations/${organizationId}/resources`}>View documents</Link></p>{data.canManage && data.jurisdiction && <form className="grid gap-3 rounded-lg border p-4" onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { await setPresentation({ organizationId, name: String(form.get("name")), reason: String(form.get("reason")) }); setMessage("Jurisdiction name saved."); } catch { setMessage("The name could not be saved. Check the fields and your access."); } finally { setSaving(false); } }}><label className="grid gap-2 text-sm font-medium">Jurisdiction name<input className={inputClass} name="name" defaultValue={data.jurisdiction.name} required maxLength={300} /></label><label className="grid gap-2 text-sm font-medium">Reason for change<input className={inputClass} name="reason" required minLength={3} maxLength={500} /></label><Button disabled={saving}>Save name</Button>{message && <p role="status" className="text-sm">{message}</p>}</form>}<p>Visibility: <strong>{data.jurisdiction?.visibility === "public" ? "Public" : "Organization members"}</strong></p><p className="text-sm text-muted-foreground">Making your jurisdiction public makes all currently published documents available to visitors and allows questions about them. Drafts and unpublished versions remain unavailable. Website chat also needs to be enabled separately.</p>{data.canManage && data.jurisdiction && <Button onClick={() => setRisk({ key: `visibility_${crypto.randomUUID()}`, visibility: data.jurisdiction!.visibility === "public" ? "members" : "public" })}>{data.jurisdiction.visibility === "public" ? "Make private" : "Make public"}</Button>}{risk && data.jurisdiction && <StepUpDialog open title={risk.visibility === "public" ? "Make jurisdiction public" : "Make jurisdiction private"} description="Verify your password to change who can access published documents. Making it private also stops website chat." submitLabel="Change visibility" cancelLabel="Keep current visibility" targetId={data.jurisdiction.id} idempotencyKey={risk.key} stepUpAction="organization_visibility" confirmationPhrase={`${risk.visibility === "public" ? "PUBLIC" : "PRIVATE"} ${data.jurisdiction.id}`} onClose={() => setRisk(null)} onConfirmed={async input => { await setVisibility({ organizationId, visibility: risk.visibility, confirmation: input.confirmation ?? "", idempotencyKey: risk.key }); setRisk(null); }} />}</div>;
}

function PublicationStatus({ versionId }: { versionId: Id<"documentVersions"> }) {
  const job = useQuery(organizationApi.organizationContent.publicationStatus, { versionId });
  const retry = useMutation(organizationApi.organizationContent.retryPublication);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  if (!job) return null;
  return <div className="space-y-2 rounded border p-3 text-sm"><p>Publication: {job.status.replaceAll("_", " ")}</p>{job.canRetry && <Button size="sm" variant="outline" disabled={busy} onClick={async () => { setBusy(true); try { await retry({ jobId: job.id, reason: "Resume known publication operation", idempotencyKey: `retry_${crypto.randomUUID()}` }); setMessage("Publication check resumed."); } catch { setMessage("This operation couldn't be resumed safely. Contact your platform administrator."); } finally { setBusy(false); } }}>Retry safely</Button>}{message && <p role="status">{message}</p>}</div>;
}

function ResourceSettings({ resource }: { resource: FunctionReturnType<typeof organizationApi.organizationContent.getResource>["resource"] }) {
  const update = useMutation(organizationApi.organizationContent.updateResource), archive = useMutation(organizationApi.organizationContent.archiveResource);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  if (resource.status === "archived") return null;
  return <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">Edit document details</summary><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={async event => { event.preventDefault(); const f = new FormData(event.currentTarget), value = (name: string) => String(f.get(name) ?? ""); const action = (event.nativeEvent as SubmitEvent).submitter?.getAttribute("value"); setBusy(true); try { if (action === "archive") await archive({ id: resource._id, reason: value("reason") }); else await update({ id: resource._id, title: value("title"), issuer: value("issuer"), officialCitation: value("officialCitation"), sourceUrl: value("sourceUrl"), effectiveDate: value("effectiveDate"), topics: resource.topics, reason: value("reason") }); setMessage(action === "archive" ? "Document archived." : "Document updated."); } catch { setMessage("The change couldn't be saved. Check the fields and ensure publication is finished. Published documents must be unpublished before archiving."); } finally { setBusy(false); } }}>
    {[["title", "Title", resource.title], ["issuer", "Issuing organization", resource.issuer], ["officialCitation", "Official citation or reference", resource.officialCitation], ["sourceUrl", "Official source URL", resource.sourceUrl], ["effectiveDate", "Effective date", resource.effectiveDate], ["reason", "Reason for change", ""]].map(([name, label, value]) => <label key={name} className="grid gap-2 text-sm font-medium">{label}<input className={inputClass} name={name} type={name === "effectiveDate" ? "date" : name === "sourceUrl" ? "url" : "text"} defaultValue={value} required minLength={name === "reason" ? 3 : undefined} maxLength={500} /></label>)}<div className="flex flex-wrap gap-3"><Button disabled={busy} value="save">Save document</Button><Button disabled={busy || !!resource.activeVersionId} variant="outline" value="archive">Archive document</Button></div>{message && <p role="status" className="text-sm">{message}</p>}
  </form></details>;
}