import { z } from "zod";
import { deepFreeze, type SplitThinkingPolicy, type StageRequest } from "./contracts";
import { GOOGLE_PROVIDER_SETTINGS } from "./google-provider-settings";

export { GOOGLE_PROVIDER_SETTINGS } from "./google-provider-settings";

export class WireFailure extends Error { constructor(readonly code: string) { super(code); } }
const fail = (code: string): never => { throw new WireFailure(code); };
const count = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const modality = z.strictObject({ modality: z.string().min(1).max(32), tokens: count });
const invocation = z.strictObject({ prompt_tokens_details: z.array(modality).max(16).optional(),
  candidates_tokens_details: z.array(modality).max(16).optional(), thoughts_tokens_details: z.array(modality).max(16).optional() });
const usageSchema = z.strictObject({ total_input_tokens: count, total_output_tokens: count, total_thought_tokens: count,
  total_cached_tokens: count, total_tool_use_tokens: count, total_tokens: count,
  input_tokens_by_modality: z.array(modality).max(16).optional(), output_tokens_by_modality: z.array(modality).max(16).optional(),
  raw_prompt_token: count.optional(), model_invocation_token_counts: z.array(invocation).max(128).optional(),
  non_grounding_model_invocation_token_counts: z.array(invocation).max(128).optional() });
const text = z.strictObject({ type: z.literal("text"), text: z.string() });
const step = z.union([
  z.strictObject({ type: z.literal("thought"), signature: z.string().optional(), summary: z.array(z.never()).optional() }),
  z.strictObject({ type: z.literal("model_output"), content: z.array(text).length(1) }),
]);
const envelopeSchema = z.strictObject({ status: z.literal("completed"), model: z.literal("gemini-3.8-flash"),
  steps: z.array(step).min(1).max(128), usage: usageSchema, object: z.literal("interaction").optional(),
  id: z.string().min(1).max(256).optional(), created: z.union([z.string().max(128), count]).optional(),
  updated: z.union([z.string().max(128), count]).optional(), service_tier: z.string().max(64).optional(),
  errors: z.array(z.never()).optional() });

/** Strict JSON for envelopes and persistent records: reject decoded duplicate
 * keys and invalid Unicode rather than accepting JSON.parse's last value. */
export function strictJson(raw: string): unknown {
  let value: unknown;
  try { value = JSON.parse(raw); } catch { return fail("malformed_json"); }
  const containers: (Set<string> | null)[] = [], tokens = /"(?:\\[\s\S]|[^"\\])*"|[{}\[\]]/g;
  let token: RegExpExecArray | null;
  while ((token = tokens.exec(raw))) {
    if (token[0] === "{") containers.push(new Set());
    else if (token[0] === "[") containers.push(null);
    else if (["}", "]"].includes(token[0])) containers.pop();
    else {
      let next = tokens.lastIndex; while (/\s/.test(raw[next] ?? "") && next < raw.length) next++;
      const keys = containers[containers.length - 1];
      if (keys && raw[next] === ":") { const key: string = JSON.parse(token[0]); if (keys.has(key)) fail("duplicate_json_key"); keys.add(key); }
    }
  }
  function unicode(item: unknown): boolean {
    if (typeof item === "string") {
      for (let i = 0; i < item.length; i++) {
        const unit = item.charCodeAt(i);
        if (unit >= 0xd800 && unit <= 0xdbff) { const next = item.charCodeAt(++i); if (!(next >= 0xdc00 && next <= 0xdfff)) return false; }
        else if (unit >= 0xdc00 && unit <= 0xdfff) return false;
      }
      return true;
    }
    return !item || typeof item !== "object" || Object.entries(item).every(([key, child]) => unicode(key) && unicode(child));
  }
  if (!unicode(value)) fail("invalid_unicode");
  return value;
}

/** Only the constructs generated by the three split contracts are admitted.
 * String constraints stay in local validation; upper array bounds are omitted
 * as the historical complexity mitigation, not as an unsupported-keyword claim.
 * New schema constructs require an explicit compatibility review. */
function providerSchema(value: unknown): Record<string, unknown> {
  const object = (item: unknown): item is Record<string, unknown> => !!item && typeof item === "object" && !Array.isArray(item);
  if (!object(value)) return fail("provider_schema_rejected");
  const allowed = value.type === "object" ? ["type", "properties", "required", "additionalProperties"]
    : value.type === "array" ? ["type", "items", "minItems", "maxItems"]
    : value.type === "string" ? ["type", "enum", "const", "minLength", "maxLength", "pattern"] : [];
  if (!allowed.length || Object.keys(value).some(key => key !== "$schema" && !allowed.includes(key))) return fail("provider_schema_rejected");
  if (value.type === "object" && (!object(value.properties) || !Array.isArray(value.required)
    || value.additionalProperties !== false)) return fail("provider_schema_rejected");
  if (value.type === "array" && !object(value.items)) return fail("provider_schema_rejected");
  const projected: Record<string, unknown> = {};
  for (const [key, item] of Object.entries(value)) {
    if (key === "$schema" || key === "pattern") {
      if (typeof item !== "string") return fail("provider_schema_rejected");
    } else if (["minLength", "maxLength", "minItems", "maxItems"].includes(key)) {
      if (typeof item !== "number" || !Number.isSafeInteger(item) || item < 0) return fail("provider_schema_rejected");
      if (key === "minItems") projected[key] = item;
    } else if (key === "const") {
      if (typeof item !== "string" || "enum" in value) return fail("provider_schema_rejected");
      projected.enum = [item];
    } else if (key === "enum" || key === "required") {
      if (!Array.isArray(item) || item.some(entry => typeof entry !== "string")
        || (key === "enum" && item.length === 0)) return fail("provider_schema_rejected");
      projected[key] = [...item];
    } else if (key === "properties") {
      if (!object(item)) return fail("provider_schema_rejected");
      projected[key] = Object.fromEntries(Object.entries(item).map(([name, child]) => [name, providerSchema(child)]));
    } else if (key === "items") projected[key] = providerSchema(item);
    else projected[key] = item;
  }
  return projected;
}

export function serializeGoogleBody(request: StageRequest, thinkingPolicy: SplitThinkingPolicy = "medium"): string {
  const expectedThinking = request.stage === "inventory" && thinkingPolicy === "inventory_low" ? "low" : "medium";
  if ((thinkingPolicy !== "medium" && thinkingPolicy !== "inventory_low")
    || request.generation_config.thinking_level !== expectedThinking || request.generation_config.max_output_tokens !== 8192
    || Object.keys(request.generation_config).length !== 2) fail("generation_settings_changed");
  const body = JSON.stringify({ model: GOOGLE_PROVIDER_SETTINGS.model, input: JSON.stringify(request.data), system_instruction: request.systemInstruction,
    tools: [], store: false, stream: false,
    generation_config: { thinking_level: request.generation_config.thinking_level, thinking_summaries: "none", tool_choice: "none", max_output_tokens: 8192 },
    response_format: { type: "text", mime_type: "application/json", schema: providerSchema(request.responseSchema) } });
  if (Buffer.byteLength(body, "utf8") > GOOGLE_PROVIDER_SETTINGS.maxWireBytes) fail("final_body_limit");
  return body;
}

export function secretDetected(raw: string, credential: string): boolean {
  const variants = [credential, encodeURIComponent(credential), Buffer.from(credential).toString("base64"), Buffer.from(credential).toString("base64url")];
  const matches = (value: string) => variants.some(variant => value.includes(variant));
  // Model JSON is itself a JSON string in the provider envelope. Inspect bounded
  // decoded layers so Unicode escapes inside that inner JSON cannot survive as
  // doubly escaped credentials in exact-capture artifacts.
  let frontier = [raw]; const seen = new Set<string>();
  for (let depth = 0; depth < 4; depth++) {
    const next: string[] = [];
    for (const value of frontier) {
      if (seen.has(value)) continue; seen.add(value);
      if (matches(value)) return true;
      try {
        const decoded = decodeURIComponent(value);
        if (matches(decoded)) return true;
        if (decoded !== value) next.push(decoded);
      } catch { /* malformed URI is still scanned as JSON */ }
      const tokens = value.match(/"(?:\\[\s\S]|[^"\\])*"/g) ?? [];
      for (const token of tokens) {
        try { const decoded: unknown = JSON.parse(token); if (typeof decoded === "string") { if (matches(decoded)) return true; next.push(decoded); } }
        catch { /* truncated token */ }
      }
    }
    frontier = next;
  }
  return false;
}

export function assertNoCredential(raw: string, credential: string): void {
  if (secretDetected(raw, credential)) fail("credential_echo");
}

export function parseProviderResponse(raw: string) {
  const parsed = envelopeSchema.safeParse(strictJson(raw));
  if (!parsed.success) return fail("provider_envelope_rejected");
  const value = parsed.data, outputs = value.steps.filter(s => s.type === "model_output");
  if (outputs.length !== 1 || outputs[0].type !== "model_output") fail("ambiguous_model_output");
  const json = outputs[0].content[0].text;
  if (Buffer.byteLength(json, "utf8") > GOOGLE_PROVIDER_SETTINGS.maxModelJsonBytes) fail("model_json_limit");
  const usage = value.usage;
  const total = usage.total_input_tokens + usage.total_output_tokens + usage.total_thought_tokens + usage.total_tool_use_tokens;
  if (!Number.isSafeInteger(total) || total !== usage.total_tokens || usage.total_cached_tokens > usage.total_input_tokens
    || usage.total_tool_use_tokens !== 0 || usage.total_output_tokens + usage.total_thought_tokens > GOOGLE_PROVIDER_SETTINGS.maxOutputTokens) fail("usage_rejected");
  return deepFreeze({ json, usage: { input: usage.total_input_tokens, output: usage.total_output_tokens, thought: usage.total_thought_tokens },
    publicUsage: usage, providerStatus: "completed" as const });
}

