"use client";
import { api } from "../../../convex/_generated/api";
import type { Id } from "../../../convex/_generated/dataModel";
import { useMutation, usePaginatedQuery } from "convex/react";
import { useState, type FormEvent } from "react";

export function IncidentActions({ incidentId, canWrite }: { incidentId: Id<"systemIncidents">; canWrite: boolean }) {
  const update = useMutation(api.admin.operations.updateIncident); const addNote = useMutation(api.admin.operations.addIncidentNote);
  const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  const timeline = usePaginatedQuery(api.admin.operations.listIncidentTimeline, open ? { incidentId } : "skip", { initialNumItems: 20 });
  async function change(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await update({ incidentId, status: String(form.get("status")) as "open" | "investigating" | "monitoring" | "resolved", severity: String(form.get("severity")) as "low" | "medium" | "high" | "critical", ownerId: String(form.get("ownerId") || "") || null, reason: String(form.get("reason")), idempotencyKey: `incident_${crypto.randomUUID().replaceAll("-", "")}` }); setMessage("Incident transition recorded."); } catch { setMessage("The incident transition was refused."); } }
  async function note(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await addNote({ incidentId, note: String(form.get("note")), reason: String(form.get("reason")), idempotencyKey: `incident_note_${crypto.randomUUID().replaceAll("-", "")}` }); setMessage("Immutable note appended."); } catch { setMessage("The note could not be appended."); } }
  return <details onToggle={(event) => setOpen(event.currentTarget.open)}><summary className="min-h-11 cursor-pointer py-3 font-semibold">Timeline and controls</summary>{open ? <div className="grid min-w-72 gap-4"><ol aria-label="Incident timeline" className="border-l-2 border-amber-700 pl-4">{timeline.results.map((item) => <li key={item.id} className="py-2"><span className="font-semibold">{item.kind}</span><span className="block text-xs">{item.summary}</span></li>)}</ol>{timeline.status === "CanLoadMore" ? <button type="button" onClick={() => timeline.loadMore(20)} className="min-h-11 underline">Load older timeline</button> : null}{canWrite ? <><form onSubmit={change} className="grid gap-2"><select aria-label="Incident status" name="status" required className="min-h-11 border px-2"><option value="open">Open</option><option value="investigating">Investigating</option><option value="monitoring">Monitoring</option><option value="resolved">Resolved</option></select><select aria-label="Incident severity" name="severity" required className="min-h-11 border px-2"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><input aria-label="Assign owner ID" name="ownerId" className="min-h-11 border px-2" /><textarea aria-label="Reason for incident transition" name="reason" required minLength={3} maxLength={500} className="min-h-20 border p-2" /><button className="min-h-11 border border-slate-700 font-semibold">Record transition</button></form><form onSubmit={note} className="grid gap-2"><textarea aria-label="Immutable incident note" name="note" required minLength={3} maxLength={500} className="min-h-20 border p-2" /><textarea aria-label="Reason for incident note" name="reason" required minLength={3} maxLength={500} className="min-h-20 border p-2" /><button className="min-h-11 border border-slate-700 font-semibold">Append note</button></form></> : null}{message ? <p role="status">{message}</p> : null}</div> : null}</details>;
}
